name: Peregrine CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache GLFW
      id: cache-glfw
      if: runner.os == 'Linux'
      uses: actions/cache@v2
      with:
        path: subprojects/glfw-3.3.6
        key: ${{ runner.os }}-glfw
    - name: configure
      run: make configure
    - name: make
      run: make
    - name: make check
      run: make check
    # TODO: YAGNI distributable checks?
    # - name: make distcheck
    #   run: make distcheck
